name: Replenish
version: '1.0.0'
main: com.asintoto.replenish.Replenish
api-version: '1.21'
authors: [ Asintoto ]
description: Crop replanting plugin
commands:
  replenish:
    description: "Main Replenish Command"
    permission: "replenish.command.use"